apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/andywatts/k8s-apps
      revision: main
      directories:
      - path: apps/*/overlays/dev
  template:
    metadata:
      name: 'dev-{{path[1]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/andywatts/k8s-apps
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[1]}}-dev'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

