apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-cluster-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      # Apps that live in their own repos
      - app: sample-app
        cluster: staging
        project: sample-app
        repoURL: https://github.com/andywatts/sample-app
        path: chart
        valuesFile: ../environments/values-staging.yaml
      # Platform infrastructure (Kong) in k8s-infra repo
      - app: kong
        cluster: staging
        project: kong
        repoURL: https://github.com/andywatts/k8s-infra
        path: charts/kong
        valuesFile: values/staging/kong.yaml
  template:
    metadata:
      name: '{{cluster}}-{{app}}'
    spec:
      project: '{{project}}'
      source:
        repoURL: '{{repoURL}}'
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
          - '{{valuesFile}}'
      destination:
        # Update this server URL when staging cluster is created
        server: https://kubernetes.default.svc
        namespace: '{{app}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
